CREATE INDEX  "GETTY_API_INDX_01" ON  "GETTY_API" ("ID", SUBSTR("TITLE",1,1000))
/
CREATE INDEX  "GETTY_API_INDX_02" ON  "GETTY_API" ("ID")
/
CREATE UNIQUE INDEX  "GETTY_IMAGES_BLOB_PK" ON  "GETTY_IMAGES_BLOB" ("ID")
/
CREATE UNIQUE INDEX  "GETTY_IPTC_COMMANDS_PK" ON  "GETTY_IPTC_COMMANDS" ("ID")
/
CREATE UNIQUE INDEX  "IMAGE_PK" ON  "GETTYIMAGES_DEMO_IMAGEBLOBS" ("ID")
/
