CREATE TABLE  "AWS_JSON" 
   (	"DOC" CLOB, 
	 CONSTRAINT "VALID_AWS_JSON" CHECK (doc is json) ENABLE
   )
/
CREATE TABLE  "AWS_URL_TAB" 
   (	"URL_NAME" VARCHAR2(2000), 
	"URL" "SYS"."URITYPE" 
   )
/
CREATE TABLE  "AWS_XML" 
   (	"XML_DATA" "XMLTYPE"
   )
/
CREATE TABLE  "FILES_XT" 
   (	"FILE_DATE" VARCHAR2(50), 
	"FILE_TIME" VARCHAR2(50), 
	"FILE_SIZE" VARCHAR2(50), 
	"FILE_NAME" VARCHAR2(255)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "XT_DIR"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        LOAD WHEN file_size != '<DIR>'
        PREPROCESSOR bin_dir: 'list_files.bat'
        FIELDS TERMINATED BY WHITESPACE
         )
      LOCATION
       ( 'sticky.txt'
       )
    )
   REJECT LIMIT UNLIMITED
/
CREATE TABLE  "GETTYIMAGES_DEMO_IMAGEBLOBS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"IMAGE_NAME" VARCHAR2(90) NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(400), 
	"MIME_TYPE" VARCHAR2(48), 
	"DOC_SIZE" NUMBER, 
	"CONTENT_TYPE" VARCHAR2(128), 
	"CONTENT" BLOB, 
	 CONSTRAINT "IMAGE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "GETTY_API" 
   (	"ID" VARCHAR2(4000), 
	"USERNAME" VARCHAR2(155), 
	"ARTIST" VARCHAR2(4000), 
	"ASSET_FAMILY" VARCHAR2(4000), 
	"CAPTION" VARCHAR2(4000), 
	"COLLECTION_CODE" VARCHAR2(4000), 
	"COLLECTION_ID" VARCHAR2(4000), 
	"COLLECTION_NAME" VARCHAR2(4000), 
	"LICENSE_MODEL" VARCHAR2(4000), 
	"MAX_DIMENSIONS" VARCHAR2(4000), 
	"TITLE" VARCHAR2(4000), 
	"IR_KEYWORDS_TEXT" VARCHAR2(4000), 
	"LINKS_URI" VARCHAR2(4000), 
	"DISPLAY_SIZES_NAME" VARCHAR2(50), 
	"LOAD_DATE" DATE
   )
/
CREATE TABLE  "GETTY_API_05AUG2015" 
   (	"ID" VARCHAR2(4000), 
	"USERNAME" VARCHAR2(155), 
	"ARTIST" VARCHAR2(4000), 
	"ASSET_FAMILY" VARCHAR2(4000), 
	"CAPTION" VARCHAR2(4000), 
	"COLLECTION_CODE" VARCHAR2(4000), 
	"COLLECTION_ID" VARCHAR2(4000), 
	"COLLECTION_NAME" VARCHAR2(4000), 
	"LICENSE_MODEL" VARCHAR2(4000), 
	"MAX_DIMENSIONS" VARCHAR2(4000), 
	"TITLE" VARCHAR2(4000), 
	"IR_KEYWORDS_TEXT" VARCHAR2(4000), 
	"LINKS_URI" VARCHAR2(4000), 
	"DISPLAY_SIZES_NAME" VARCHAR2(50)
   )
/
CREATE TABLE  "GETTY_API_14JUL2015" 
   (	"ID" VARCHAR2(4000), 
	"USERNAME" VARCHAR2(155), 
	"ARTIST" VARCHAR2(4000), 
	"ASSET_FAMILY" VARCHAR2(4000), 
	"CAPTION" VARCHAR2(4000), 
	"COLLECTION_CODE" VARCHAR2(4000), 
	"COLLECTION_ID" VARCHAR2(4000), 
	"COLLECTION_NAME" VARCHAR2(4000), 
	"LICENSE_MODEL" VARCHAR2(4000), 
	"MAX_DIMENSIONS" VARCHAR2(4000), 
	"TITLE" VARCHAR2(4000), 
	"IR_KEYWORDS_TEXT" VARCHAR2(4000), 
	"LINKS_URI" VARCHAR2(4000), 
	"DISPLAY_SIZES_NAME" VARCHAR2(50)
   )
/
CREATE TABLE  "GETTY_API_ARCH" 
   (	"ID" VARCHAR2(4000), 
	"USERNAME" VARCHAR2(155), 
	"ARTIST" VARCHAR2(4000), 
	"ASSET_FAMILY" VARCHAR2(4000), 
	"CAPTION" VARCHAR2(4000), 
	"COLLECTION_CODE" VARCHAR2(4000), 
	"COLLECTION_ID" VARCHAR2(4000), 
	"COLLECTION_NAME" VARCHAR2(4000), 
	"LICENSE_MODEL" VARCHAR2(4000), 
	"MAX_DIMENSIONS" VARCHAR2(4000), 
	"TITLE" VARCHAR2(4000), 
	"IR_KEYWORDS_TEXT" VARCHAR2(4000), 
	"LINKS_URI" VARCHAR2(4000), 
	"DISPLAY_SIZES_NAME" VARCHAR2(50)
   )
/
CREATE TABLE  "GETTY_API_ONE_OFF" 
   (	"ID" VARCHAR2(4000), 
	"USERNAME" VARCHAR2(155), 
	"ARTIST" VARCHAR2(4000), 
	"ASSET_FAMILY" VARCHAR2(4000), 
	"CAPTION" VARCHAR2(4000), 
	"COLLECTION_CODE" VARCHAR2(4000), 
	"COLLECTION_ID" VARCHAR2(4000), 
	"COLLECTION_NAME" VARCHAR2(4000), 
	"LICENSE_MODEL" VARCHAR2(4000), 
	"MAX_DIMENSIONS" VARCHAR2(4000), 
	"TITLE" VARCHAR2(4000), 
	"IR_KEYWORDS_TEXT" VARCHAR2(4000), 
	"LINKS_URI" VARCHAR2(4000), 
	"DISPLAY_SIZES_NAME" VARCHAR2(50)
   )
/
CREATE TABLE  "GETTY_API_ORIG" 
   (	"ID" VARCHAR2(4000), 
	"USERNAME" VARCHAR2(30), 
	"ARTIST" VARCHAR2(4000), 
	"ASSET_FAMILY" VARCHAR2(4000), 
	"CAPTION" VARCHAR2(4000), 
	"COLLECTION_CODE" VARCHAR2(4000), 
	"COLLECTION_ID" VARCHAR2(4000), 
	"COLLECTION_NAME" VARCHAR2(4000), 
	"LICENSE_MODEL" VARCHAR2(4000), 
	"MAX_DIMENSIONS" VARCHAR2(4000), 
	"TITLE" VARCHAR2(4000), 
	"IR_KEYWORDS_TEXT" VARCHAR2(4000)
   )
/
CREATE TABLE  "GETTY_EPS_API" 
   (	"ID" VARCHAR2(4000), 
	"USERNAME" VARCHAR2(155), 
	"ARTIST" VARCHAR2(4000), 
	"ASSET_FAMILY" VARCHAR2(4000), 
	"CAPTION" VARCHAR2(4000), 
	"COLLECTION_CODE" VARCHAR2(4000), 
	"COLLECTION_ID" VARCHAR2(4000), 
	"COLLECTION_NAME" VARCHAR2(4000), 
	"LICENSE_MODEL" VARCHAR2(4000), 
	"MAX_DIMENSIONS" VARCHAR2(4000), 
	"TITLE" VARCHAR2(4000), 
	"IR_KEYWORDS_TEXT" VARCHAR2(4000), 
	"LINKS_URI" VARCHAR2(4000), 
	"DISPLAY_SIZES_NAME" VARCHAR2(50)
   )
/
CREATE TABLE  "GETTY_EPS_DEMO_IMAGEBLOBS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"IMAGE_NAME" VARCHAR2(90) NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(400), 
	"MIME_TYPE" VARCHAR2(48), 
	"DOC_SIZE" NUMBER, 
	"CONTENT_TYPE" VARCHAR2(128), 
	"CONTENT" BLOB
   )
/
CREATE TABLE  "GETTY_EPS_IMAGES_BLOB" 
   (	"ID" NUMBER(10,0), 
	"URL" VARCHAR2(1000), 
	"DATA" BLOB, 
	"IMAGE_NAME" VARCHAR2(500), 
	"MODIFIED_DATE" DATE
   )
/
CREATE TABLE  "GETTY_EPS_USER_DOWNLOADS" 
   (	"GUD_ID" NUMBER, 
	"USERNAME" VARCHAR2(75), 
	"INDIVIDUAL_NAME" VARCHAR2(255), 
	"MASTER_ID" VARCHAR2(80), 
	"COLLECTION" VARCHAR2(80), 
	"DOWNLOAD_DATE" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(4000), 
	"CAPTION" VARCHAR2(4000), 
	"WEBSITE" VARCHAR2(255), 
	"LOAD_DATE" TIMESTAMP (6), 
	"IMAGE_DOWNLOAD_DATE" DATE
   )
/
CREATE TABLE  "GETTY_IMAGES_BLOB" 
   (	"ID" NUMBER(10,0), 
	"URL" VARCHAR2(1000), 
	"DATA" BLOB, 
	"IMAGE_NAME" VARCHAR2(500), 
	"MODIFIED_DATE" DATE, 
	 CONSTRAINT "GETTY_IMAGES_BLOB_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "GETTY_IMAGES_BLOB_ARCH" 
   (	"ID" NUMBER(10,0), 
	"URL" VARCHAR2(1000), 
	"DATA" BLOB, 
	"IMAGE_NAME" VARCHAR2(500), 
	"MODIFIED_DATE" DATE
   )
/
CREATE TABLE  "GETTY_IMAGES_RUN_HISTORY" 
   (	"ID" NUMBER, 
	"IMAGE_ID" VARCHAR2(255), 
	"START_IMAGE_PULL" DATE, 
	"END_IMAGE_PULL" DATE
   )
/
CREATE TABLE  "GETTY_IPTC_COMMANDS" 
   (	"ID" NUMBER, 
	"IPTC_TYPE" VARCHAR2(100), 
	"IPTC_COMMAND" VARCHAR2(4000), 
	"CMD_RUN_DATE" DATE, 
	"MASTER_ID" VARCHAR2(255), 
	 CONSTRAINT "GETTY_IPTC_COMMANDS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "GETTY_IPTC_COMMANDS_15SEP" 
   (	"ID" NUMBER, 
	"IPTC_TYPE" VARCHAR2(100), 
	"IPTC_COMMAND" VARCHAR2(4000), 
	"CMD_RUN_DATE" DATE, 
	"MASTER_ID" VARCHAR2(255)
   )
/
CREATE TABLE  "GETTY_IPTC_COMMANDS_20SEP2016" 
   (	"ID" NUMBER, 
	"IPTC_TYPE" VARCHAR2(100), 
	"IPTC_COMMAND" VARCHAR2(4000), 
	"CMD_RUN_DATE" DATE, 
	"MASTER_ID" VARCHAR2(255)
   )
/
CREATE TABLE  "GETTY_IR_TEMP" 
   (	"ID" VARCHAR2(55)
   )
/
CREATE TABLE  "GETTY_MISSING_DOWNLOAD_IMAGES" 
   (	"IMAGE" VARCHAR2(500)
   )
/
CREATE TABLE  "GETTY_TMP_EPS_FILES" 
   (	"MASTER_ID" NUMBER
   )
/
CREATE TABLE  "GETTY_TOKEN" 
   (	"TOKEN" VARCHAR2(4000)
   )
/
CREATE TABLE  "GETTY_USER_DOWNLOADS" 
   (	"GUD_ID" NUMBER, 
	"USERNAME" VARCHAR2(75), 
	"INDIVIDUAL_NAME" VARCHAR2(255), 
	"MASTER_ID" VARCHAR2(80), 
	"COLLECTION" VARCHAR2(80), 
	"DOWNLOAD_DATE" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(4000), 
	"CAPTION" VARCHAR2(4000), 
	"WEBSITE" VARCHAR2(255), 
	"LOAD_DATE" TIMESTAMP (6), 
	"IMAGE_DOWNLOAD_DATE" DATE, 
	"KEYWORDS_LOAD_DATE" DATE, 
	"TITLE_LOAD_DATE" DATE
   )
/
CREATE TABLE  "GETTY_USER_DOWNLOADS_05AUG2015" 
   (	"GUD_ID" NUMBER, 
	"USERNAME" VARCHAR2(75), 
	"INDIVIDUAL_NAME" VARCHAR2(255), 
	"MASTER_ID" VARCHAR2(80), 
	"COLLECTION" VARCHAR2(80), 
	"DOWNLOAD_DATE" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(4000), 
	"CAPTION" VARCHAR2(4000), 
	"WEBSITE" VARCHAR2(255), 
	"LOAD_DATE" TIMESTAMP (6), 
	"IMAGE_DOWNLOAD_DATE" DATE
   )
/
CREATE TABLE  "GETTY_USER_DOWNLOADS_15SEP" 
   (	"GUD_ID" NUMBER, 
	"USERNAME" VARCHAR2(75), 
	"INDIVIDUAL_NAME" VARCHAR2(255), 
	"MASTER_ID" VARCHAR2(80), 
	"COLLECTION" VARCHAR2(80), 
	"DOWNLOAD_DATE" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(4000), 
	"CAPTION" VARCHAR2(4000), 
	"WEBSITE" VARCHAR2(255), 
	"LOAD_DATE" TIMESTAMP (6), 
	"IMAGE_DOWNLOAD_DATE" DATE, 
	"KEYWORDS_LOAD_DATE" DATE, 
	"TITLE_LOAD_DATE" DATE
   )
/
CREATE TABLE  "GETTY_USER_DOWNLOADS_19SEP2016" 
   (	"GUD_ID" NUMBER, 
	"USERNAME" VARCHAR2(75), 
	"INDIVIDUAL_NAME" VARCHAR2(255), 
	"MASTER_ID" VARCHAR2(80), 
	"COLLECTION" VARCHAR2(80), 
	"DOWNLOAD_DATE" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(4000), 
	"CAPTION" VARCHAR2(4000), 
	"WEBSITE" VARCHAR2(255), 
	"LOAD_DATE" TIMESTAMP (6), 
	"IMAGE_DOWNLOAD_DATE" DATE, 
	"KEYWORDS_LOAD_DATE" DATE, 
	"TITLE_LOAD_DATE" DATE
   )
/
CREATE TABLE  "GETTY_USER_DOWNLOADS_20SEP2016" 
   (	"GUD_ID" NUMBER, 
	"USERNAME" VARCHAR2(75), 
	"INDIVIDUAL_NAME" VARCHAR2(255), 
	"MASTER_ID" VARCHAR2(80), 
	"COLLECTION" VARCHAR2(80), 
	"DOWNLOAD_DATE" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(4000), 
	"CAPTION" VARCHAR2(4000), 
	"WEBSITE" VARCHAR2(255), 
	"LOAD_DATE" TIMESTAMP (6), 
	"IMAGE_DOWNLOAD_DATE" DATE, 
	"KEYWORDS_LOAD_DATE" DATE, 
	"TITLE_LOAD_DATE" DATE
   )
/
CREATE TABLE  "GETTY_USER_DOWNLOADS_ARCH" 
   (	"GUD_ID" NUMBER, 
	"USERNAME" VARCHAR2(75), 
	"INDIVIDUAL_NAME" VARCHAR2(255), 
	"MASTER_ID" VARCHAR2(80), 
	"COLLECTION" VARCHAR2(80), 
	"DOWNLOAD_DATE" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(4000), 
	"CAPTION" VARCHAR2(4000), 
	"WEBSITE" VARCHAR2(255), 
	"LOAD_DATE" TIMESTAMP (6), 
	"IMAGE_DOWNLOAD_DATE" DATE
   )
/
CREATE TABLE  "GETTY_USER_DOWNLOADS_NEW" 
   (	"GUD_ID" NUMBER, 
	"USERNAME" VARCHAR2(75), 
	"INDIVIDUAL_NAME" VARCHAR2(255), 
	"MASTER_ID" VARCHAR2(80), 
	"COLLECTION" VARCHAR2(80), 
	"DOWNLOAD_DATE" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(4000), 
	"CAPTION" VARCHAR2(4000), 
	"WEBSITE" VARCHAR2(255), 
	"LOAD_DATE" TIMESTAMP (6)
   )
/
CREATE TABLE  "GETTY_USER_DOWNLOADS_ORIG" 
   (	"GUD_ID" NUMBER, 
	"USERNAME" VARCHAR2(30), 
	"INDIVIDUAL_NAME" VARCHAR2(255), 
	"MASTER_ID" VARCHAR2(80), 
	"COLLECTION" VARCHAR2(80), 
	"DOWNLOAD_DATE" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(4000), 
	"CAPTION" VARCHAR2(4000), 
	"WEBSITE" VARCHAR2(255), 
	"LOAD_DATE" TIMESTAMP (6)
   )
/
CREATE TABLE  "GETTY_USER_JOBS_05AUG2015" 
   (	"JOB" NUMBER NOT NULL ENABLE, 
	"LOG_USER" VARCHAR2(128) NOT NULL ENABLE, 
	"PRIV_USER" VARCHAR2(128) NOT NULL ENABLE, 
	"SCHEMA_USER" VARCHAR2(128) NOT NULL ENABLE, 
	"LAST_DATE" DATE, 
	"LAST_SEC" VARCHAR2(8), 
	"THIS_DATE" DATE, 
	"THIS_SEC" VARCHAR2(8), 
	"NEXT_DATE" DATE NOT NULL ENABLE, 
	"NEXT_SEC" VARCHAR2(8), 
	"TOTAL_TIME" NUMBER, 
	"BROKEN" VARCHAR2(1), 
	"INTERVAL" VARCHAR2(200) NOT NULL ENABLE, 
	"FAILURES" NUMBER, 
	"WHAT" VARCHAR2(4000), 
	"NLS_ENV" VARCHAR2(4000), 
	"MISC_ENV" RAW(32), 
	"INSTANCE" NUMBER
   )
/
CREATE TABLE  "HTMLDB_PLAN_TABLE" 
   (	"STATEMENT_ID" VARCHAR2(30), 
	"PLAN_ID" NUMBER, 
	"TIMESTAMP" DATE, 
	"REMARKS" VARCHAR2(4000), 
	"OPERATION" VARCHAR2(30), 
	"OPTIONS" VARCHAR2(255), 
	"OBJECT_NODE" VARCHAR2(128), 
	"OBJECT_OWNER" VARCHAR2(30), 
	"OBJECT_NAME" VARCHAR2(30), 
	"OBJECT_ALIAS" VARCHAR2(65), 
	"OBJECT_INSTANCE" NUMBER(*,0), 
	"OBJECT_TYPE" VARCHAR2(30), 
	"OPTIMIZER" VARCHAR2(255), 
	"SEARCH_COLUMNS" NUMBER, 
	"ID" NUMBER(*,0), 
	"PARENT_ID" NUMBER(*,0), 
	"DEPTH" NUMBER(*,0), 
	"POSITION" NUMBER(*,0), 
	"COST" NUMBER(*,0), 
	"CARDINALITY" NUMBER(*,0), 
	"BYTES" NUMBER(*,0), 
	"OTHER_TAG" VARCHAR2(255), 
	"PARTITION_START" VARCHAR2(255), 
	"PARTITION_STOP" VARCHAR2(255), 
	"PARTITION_ID" NUMBER(*,0), 
	"OTHER" LONG, 
	"DISTRIBUTION" VARCHAR2(30), 
	"CPU_COST" NUMBER(*,0), 
	"IO_COST" NUMBER(*,0), 
	"TEMP_SPACE" NUMBER(*,0), 
	"ACCESS_PREDICATES" VARCHAR2(4000), 
	"FILTER_PREDICATES" VARCHAR2(4000), 
	"PROJECTION" VARCHAR2(4000), 
	"TIME" NUMBER(*,0), 
	"QBLOCK_NAME" VARCHAR2(30)
   )
/
CREATE TABLE  "JSON" 
   (	"DOC" CLOB, 
	 CONSTRAINT "VALID_JSON" CHECK (doc is json) ENABLE
   )
/
CREATE TABLE  "JSON_EPS" 
   (	"DOC" CLOB
   )
/
CREATE TABLE  "PERSON_DATA" 
   (	"PERSON_ID" NUMBER(3,0), 
	"PERSON_DATA" "SYS"."XMLTYPE" 
   )
/
CREATE TABLE  "TOKENS_EXT" 
   (	"IR_TOKEN" VARCHAR2(4000)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "EXT_TAB_DATA"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
    FIELDS TERMINATED BY ','
    MISSING FIELD VALUES ARE NULL
    (
      ir_token  CHAR(4000)
    )
      )
      LOCATION
       ( 'tokens1.txt', 
         'tokens2.txt'
       )
    )
   REJECT LIMIT UNLIMITED
/
CREATE TABLE  "URL_TAB" 
   (	"URL_NAME" VARCHAR2(100), 
	"URL" "SYS"."URITYPE" 
   )
/
CREATE TABLE  "XML_DATA_TAB" 
   (	"XML_DATA" "XMLTYPE"
   )
/
CREATE TABLE  "XWAREHOUSES" OF XMLTYPE 
  ALLOW NONSCHEMA DISALLOW ANYSCHEMA
/

